"""add PesertaDidik

Revision ID: 9f0e09fbedff
Revises: 51347face28e
Create Date: 2020-12-29 20:19:12.362935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0e09fbedff'
down_revision = '51347face28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peserta_didik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sekolah_id', sa.Integer(), nullable=True),
    sa.Column('registrasi_id', sa.String(), nullable=False),
    sa.Column('jenis_pendaftaran_id', sa.String(), nullable=False),
    sa.Column('jenis_pendaftaran_id_str', sa.String(), nullable=False),
    sa.Column('nipd', sa.String(), nullable=False),
    sa.Column('tanggal_masuk_sekolah', sa.String(), nullable=False),
    sa.Column('sekolah_asal', sa.String(), nullable=True),
    sa.Column('peserta_didik_id', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('nisn', sa.String(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(), nullable=False),
    sa.Column('nik', sa.String(), nullable=False),
    sa.Column('tempat_lahir', sa.String(), nullable=False),
    sa.Column('tanggal_lahir', sa.String(), nullable=False),
    sa.Column('agama_id_str', sa.String(), nullable=False),
    sa.Column('alamat_jalan', sa.String(), nullable=True),
    sa.Column('nomor_telepon_rumah', sa.String(), nullable=True),
    sa.Column('nomor_telepon_seluler', sa.String(), nullable=True),
    sa.Column('nama_ayah', sa.String(), nullable=False),
    sa.Column('pekerjaan_ayah_id_str', sa.String(), nullable=False),
    sa.Column('nama_ibu', sa.String(), nullable=False),
    sa.Column('pekerjaan_ibu_id_str', sa.String(), nullable=False),
    sa.Column('nama_wali', sa.String(), nullable=True),
    sa.Column('pekerjaan_wali_id_str', sa.String(), nullable=False),
    sa.Column('tinggi_badan', sa.String(), nullable=False),
    sa.Column('berat_badan', sa.String(), nullable=False),
    sa.Column('semester_id', sa.String(), nullable=False),
    sa.Column('anggota_rombel_id', sa.String(), nullable=False),
    sa.Column('rombongan_belajar_id', sa.String(), nullable=False),
    sa.Column('tingkat_pendidikan_id', sa.String(), nullable=False),
    sa.Column('nama_rombel', sa.String(), nullable=False),
    sa.Column('kurikulum_id', sa.String(), nullable=False),
    sa.Column('kurikulum_id_str', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], name='sekolah', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peserta_didik')
    # ### end Alembic commands ###
