"""change sekolah

Revision ID: 51347face28e
Revises: 
Create Date: 2020-12-29 19:37:25.022965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51347face28e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sekolah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_dapodik', sa.String(), nullable=True),
    sa.Column('email_dapodik', sa.String(), nullable=True),
    sa.Column('password_dapodik', sa.String(), nullable=True),
    sa.Column('email_simdak', sa.String(), nullable=True),
    sa.Column('password_simdak', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sekolah_id', sa.String(), nullable=True),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('nss', sa.String(), nullable=True),
    sa.Column('npsn', sa.String(), nullable=True),
    sa.Column('bentuk_pendidikan_id', sa.Integer(), nullable=True),
    sa.Column('bentuk_pendidikan_id_str', sa.String(), nullable=True),
    sa.Column('status_sekolah', sa.String(), nullable=True),
    sa.Column('status_sekolah_str', sa.String(), nullable=True),
    sa.Column('alamat_jalan', sa.String(), nullable=True),
    sa.Column('rt', sa.String(), nullable=True),
    sa.Column('rw', sa.String(), nullable=True),
    sa.Column('kode_wilayah', sa.String(), nullable=True),
    sa.Column('kode_pos', sa.String(), nullable=True),
    sa.Column('nomor_telepon', sa.String(), nullable=True),
    sa.Column('nomor_fax', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('is_sks', sa.Boolean(), nullable=True),
    sa.Column('lintang', sa.String(), nullable=True),
    sa.Column('bujur', sa.String(), nullable=True),
    sa.Column('dusun', sa.String(), nullable=True),
    sa.Column('desa_kelurahan', sa.String(), nullable=True),
    sa.Column('kecamatan', sa.String(), nullable=True),
    sa.Column('kabupaten_kota', sa.String(), nullable=True),
    sa.Column('provinsi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sekolah')
    # ### end Alembic commands ###
