repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        files: ^(bopku|tests)/.*\.py$
        args:
          - --diff
        exclude: bopku/alembic
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args:
          - --ignore=E501
        exclude: bopku/alembic
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0
    hooks:
      - id: pylint
        files: ^bopku/.*\.py$
        args:
          - --errors-only
          - --disable=import-error
        exclude: bopku/alembic
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.790"
    hooks:
      - id: mypy
        files: ^bopku/.*\.py$
        exclude: bopku/alembic
